DROP TABLE IF EXISTS decks;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL
);

CREATE TABLE decks (
    deck_id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    time_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deck_name TEXT NOT NULL,
    number_of_cards INTEGER NOT NULL DEFAULT 0,

    FOREIGN KEY(user_id) REFERENCES users(user_id)
);


CREATE TABLE cards (
    card_id INTEGER PRIMARY KEY AUTOINCREMENT,
    deck_id INTEGER NOT NULL,
    time_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    front TEXT NOT NULL,
    back TEXT NOT NULL,
    familiarity INTEGER NOT NULL DEFAULT 1,
    
    FOREIGN KEY(deck_id) REFERENCES decks(deck_id)
);

